### ISSUE TITLE
Match status error

### ISSUE THREAD

**Issue by bhattanil** [marcinbojko/commvault_exporter#1]
While running the exporter getting the error 
Match status:

Syntax error 

Latest version I am trying. How to resolve this one.

**Comment by marcinbojko** [comment]
Pleasy try latest dev version: https://hub.docker.com/layers/marcinbojko/commvault_exporter/0.0.5-2-dev/images/sha256-33b1a72c416c066e940f381d6605a914f691b1fb1cc5cbeb7a02adc8d9e6f477?context=repo

**Comment by bhattanil** [comment]
Can we also run standalone service, as I am not using docker in my
environment.

**Comment by marcinbojko** [comment]
Yes you can.

**Comment by bhattanil** [comment]
Hi Marcinbojko/Commvault_exporter,

I am trying to run not able to run is this user specific we should have
same user python_user only or we can run with other too.

I am trying with other user but no luck tried with docker imager to dev
also not working.

* Is you code is user specific it is checking for user
Python_user only on the server with same name *

Regards
Anil Bhatt
Monitoring tools

**Comment by marcinbojko** [comment]
I seriously have no idea what are you asking for.

**Comment by bhattanil** [comment]
Could you share steps I tried same steps I am not able to run the exporter.
In both cases docker as well as in ubuntu.

Thanks, sorry I am bothering you with this.
